name: Add a new feature
description: Make a pull request to add new functionality to the loader
title: "[enhancement] <title>"
labels: [enhancement]
body:
  - type: checkboxes
    id: low-effort-checks
    attributes:
      label: Please confirm
      description: Issues without all checks may be ignored/closed.
      options:
        - label: I have tested this code on a steam deck or on a PC

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what the new feature is. If appropriate, include screenshots or videos.
      placeholder: |
        This PR implements cool RGB lights to decky...
    validations:
      required: true
